# Generated by Django 4.2.2 on 2025-10-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_views_counter_alter_product_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "categor", "price"],
                "permissions": [
                    ("can_edit_categor", "Can edit categor"),
                    ("can_edit_description", "Can edit description"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
